#Create a ROLEBINDING in dev namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
  namespace: dev
subjects:
- kind: User
  name: Byran
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io

============================================
#Create a ROLEBINDING in testing namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
  namespace: staging
subjects:
- kind: User
  name: Byran
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: testing
  apiGroup: rbac.authorization.k8s.io

============================================
#Create a ROLEBINDING in devop's namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
  namespace: production
subjects:
- kind: User
  name: Byran
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops
  apiGroup: rbac.authorization.k8s.io